git submodule add https://github.com/tpope/vim-fugitive.git pack/third_party/start/vim-fugitive
git submodule add https://github.com/hrsh7th/cmp-buffer.git pack/third_party/start/cmp-buffer
git submodule add https://github.com/hrsh7th/cmp-nvim-lsp-signature-help.git pack/third_party/start/cmp-nvim-lsp-signature-help
git submodule add https://github.com/hrsh7th/cmp-nvim-lsp.git pack/third_party/start/cmp-nvim-lsp
git submodule add https://github.com/hrsh7th/cmp-nvim-lua.git pack/third_party/start/cmp-nvim-lua
git submodule add https://github.com/hrsh7th/cmp-path.git pack/third_party/start/cmp-path
git submodule add https://github.com/hrsh7th/cmp-vsnip.git pack/third_party/start/cmp-vsnip
git submodule add https://github.com/hrsh7th/nvim-cmp.git pack/third_party/start/nvim-cmp
git submodule add https://github.com/hrsh7th/vim-vsnip.git pack/third_party/start/vim-vsnip
git submodule add https://github.com/rcarriga/nvim-dap-ui.git pack/third_party/start/nvim-dap-ui
git submodule add https://github.com/mfussenegger/nvim-dap.git pack/third_party/start/nvim-dap
git submodule add https://github.com/neovim/nvim-lspconfig.git pack/third_party/start/nvim-lspconfig
git submodule add https://github.com/nvim-neotest/nvim-nio.git pack/third_party/start/nvim-nio
git submodule add https://github.com/nvim-treesitter/nvim-treesitter.git pack/third_party/start/nvim-treesitter
git submodule add https://github.com/navarasu/onedark.nvim.git pack/third_party/start/onedark
git submodule add https://github.com/nvim-lua/plenary.nvim.git pack/third_party/start/plenary
git submodule add https://github.com/nvim-telescope/telescope-dap.nvim.git pack/third_party/start/telescope-dap
git submodule add https://github.com/nvim-telescope/telescope-ui-select.nvim.git pack/third_party/start/telescope-ui-select
git submodule add https://github.com/nvim-telescope/telescope.nvim.git pack/third_party/start/telescope
git submodule add https://github.com/folke/trouble.nvim.git pack/third_party/start/trouble
git submodule add https://github.com/voldikss/vim-floaterm.git pack/third_party/start/vim-floaterm
git submodule add https://github.com/numToStr/Comment.nvim.git pack/third_party/start/Comment.nvim
